package com.example.core.util

object AppStrings {
    fun get(key: String, language: String = "English"): String {
        val langCode = when {
            language.equals("hi", ignoreCase = true) || language.contains("Hindi", ignoreCase = true) || language.contains("हिंदी") -> "hi"
            language.equals("mr", ignoreCase = true) || language.contains("Marathi", ignoreCase = true) || language.contains("मराठी") -> "mr"
            language.equals("gu", ignoreCase = true) || language.contains("Gujarati", ignoreCase = true) || language.contains("ગુજરાતી") -> "gu"
            language.equals("bn", ignoreCase = true) || language.contains("Bengali", ignoreCase = true) || language.contains("বাংলা") -> "bn"
            language.equals("ta", ignoreCase = true) || language.contains("Tamil", ignoreCase = true) || language.contains("தமிழ்") -> "ta"
            else -> "en"
        }

        val translations = mapOf(
            "en" to mapOf(
                "labor" to "Labor",
                "cash_book" to "Cash book",
                "settings" to "Settings",
                "add_labor" to "Add Labor",
                "add_staff" to "Add Staff",
                "non_contact_staff" to "Non-contact staff info",
                "enter_labor_name" to "Enter Labor Name",
                "mobile_number" to "Mobile Number",
                "daily_wage" to "Daily Wage",
                "search_contact" to "Search by Name or Mobile number",
                "saved_contacts" to "Your saved contacts",
                "permission_contacts_title" to "Contacts Permission Needed",
                "permission_contacts_desc" to "Allow Laborbook to access your device contacts to quickly add laborers without typing their numbers manually.",
                "allow_contacts" to "Allow Contact Access",
                "pick_from_device" to "Pick from Device Contacts",
                "refresh_contacts" to "Refresh Contacts",
                "cash_in" to "+ CASH IN",
                "cash_out" to "- CASH OUT",
                "cash_in_label" to "Cash In",
                "cash_out_label" to "Cash Out",
                "balance" to "Balance",
                "view_report" to "View Report",
                "search_transactions" to "Search transactions",
                "no_transactions" to "No transactions this month",
                "date" to "Date",
                "notes" to "Notes",
                "amount" to "₹ Amount",
                "profile_info" to "Profile Info",
                "business_name" to "Business Name",
                "account_email" to "Account / Email",
                "mobile" to "Mobile",
                "general" to "General",
                "drive_backup" to "Backup Google Drive Backup & Import Sync",
                "privacy_policy" to "Privacy Policy",
                "terms_conditions" to "Terms & Conditions",
                "rating_feedback" to "Give us Rating & Feedback",
                "logout" to "Logout",
                "select_language" to "Select Language",
                "save" to "Save",
                "cancel" to "Cancel",
                "ok" to "Ok",
                "present" to "Present",
                "absent" to "Absent",
                "half_day" to "Half Day",
                "overtime" to "Overtime",
                "calendar" to "Calendar"
            ),
            "hi" to mapOf(
                "labor" to "मजदूर",
                "cash_book" to "रोकड़ बही",
                "settings" to "सेटिंग्स",
                "add_labor" to "मजदूर जोड़ें",
                "add_staff" to "स्टाफ जोड़ें",
                "non_contact_staff" to "सीधे स्टाफ विवरण भरें",
                "enter_labor_name" to "मजदूर का नाम दर्ज करें",
                "mobile_number" to "मोबाइल नंबर",
                "daily_wage" to "दैनिक मजदूरी (₹)",
                "search_contact" to "नाम या मोबाइल नंबर से खोजें",
                "saved_contacts" to "आपके फोन संपर्क",
                "permission_contacts_title" to "संपर्क अनुमति आवश्यक है",
                "permission_contacts_desc" to "मजदूरों को सीधे फोन संपर्कों से जोड़ने के लिए अनुमति दें।",
                "allow_contacts" to "संपर्क अनुमति दें",
                "pick_from_device" to "फोन से संपर्क चुनें",
                "refresh_contacts" to "संपर्क रीफ्रेश करें",
                "cash_in" to "+ कैश इन (जमा)",
                "cash_out" to "- कैश आउट (खर्च)",
                "cash_in_label" to "कैश इन (जमा)",
                "cash_out_label" to "कैश आउट (खर्च)",
                "balance" to "कुल बैलेंस",
                "view_report" to "रिपोर्ट देखें",
                "search_transactions" to "लेनदेन खोजें",
                "no_transactions" to "इस महीने कोई लेन-देन नहीं",
                "date" to "तारीख",
                "notes" to "विवरण",
                "amount" to "₹ राशि",
                "profile_info" to "प्रोफ़ाइल जानकारी",
                "business_name" to "व्यवसाय / ठेकेदार का नाम",
                "account_email" to "खाता / ईमेल",
                "mobile" to "मोबाइल",
                "general" to "गूगल ड्राइव और सामान्य",
                "drive_backup" to "गूगल ड्राइव बैकअप और आयात",
                "privacy_policy" to "गोपनीयता नीति",
                "terms_conditions" to "नियम और शर्तें",
                "rating_feedback" to "रेटिंग और फीडबैक दें",
                "logout" to "लॉग आउट",
                "select_language" to "भाषा चुनें",
                "save" to "सहेजें",
                "cancel" to "रद्द करें",
                "ok" to "ठीक है",
                "present" to "उपस्थित (P)",
                "absent" to "अनुपस्थित (A)",
                "half_day" to "आधा दिन (HD)",
                "overtime" to "ओवरटाइम (OT)",
                "calendar" to "कैलेंडर"
            ),
            "mr" to mapOf(
                "labor" to "कामगार",
                "cash_book" to "रोकड वही",
                "settings" to "सेटिंग्ज",
                "add_labor" to "कामगार जोडा",
                "add_staff" to "कर्मचारी जोडा",
                "non_contact_staff" to "थेट कर्मचारी माहिती भरा",
                "enter_labor_name" to "कामगाराचे नाव टाका",
                "mobile_number" to "मोबाईल नंबर",
                "daily_wage" to "दैनिक मजुरी (₹)",
                "search_contact" to "नाव किंवा मोबाईल नंबरने शोधा",
                "saved_contacts" to "तुमचे सेव्ह केलेले संपर्क",
                "permission_contacts_title" to "संपर्क परवानगी आवश्यक आहे",
                "permission_contacts_desc" to "फोन संपर्कांमधून कामगार जोडण्यासाठी संपर्क परवानगी द्या.",
                "allow_contacts" to "संपर्क परवानगी द्या",
                "pick_from_device" to "फोनमधून संपर्क निवडा",
                "refresh_contacts" to "संपर्क रिफ्रेश करा",
                "cash_in" to "+ कॅश इन (जमा)",
                "cash_out" to "- कॅश आउट (खर्च)",
                "cash_in_label" to "कॅश इन (जमा)",
                "cash_out_label" to "कॅश आउट (खर्च)",
                "balance" to "शिल्लक रक्कम",
                "view_report" to "रिपोर्ट पहा",
                "search_transactions" to "व्यवहार शोधा",
                "no_transactions" to "या महिन्यात कोणतेही व्यवहार नाहीत",
                "date" to "तारीख",
                "notes" to "तपशील",
                "amount" to "₹ रक्कम",
                "profile_info" to "प्रोफाइल माहिती",
                "business_name" to "व्यवसायाचे / कंत्राटदाराचे नाव",
                "account_email" to "खाते / ईमेल",
                "mobile" to "मोबाईल",
                "general" to "गुगल ड्राइव्ह आणि सामान्य",
                "drive_backup" to "गुगल ड्राइव्ह बॅकअप आणि आयात",
                "privacy_policy" to "गोपनीयता धोरण",
                "terms_conditions" to "नियम व अटी",
                "rating_feedback" to "आम्हाला रेटिंग आणि अभिप्राय द्या",
                "logout" to "लॉग आउट",
                "select_language" to "भाषा निवडा",
                "save" to "जतन करा",
                "cancel" to "रद्द करा",
                "ok" to "ठीक आहे",
                "present" to "हजर (P)",
                "absent" to "गैरहजर (A)",
                "half_day" to "अर्धा दिवस (HD)",
                "overtime" to "ओव्हरटाईम (OT)",
                "calendar" to "कॅलेंडर"
            ),
            "gu" to mapOf(
                "labor" to "કારીગર",
                "cash_book" to "રોકડ બહી",
                "settings" to "સેટિંગ્સ",
                "add_labor" to "કારીગર ઉમેરો",
                "add_staff" to "સ્ટાફ ઉમેરો",
                "non_contact_staff" to "સ્ટાફ વિગત દાખલ કરો",
                "enter_labor_name" to "કારીગરનું નામ દાખલ કરો",
                "mobile_number" to "મોબાઇલ નંબર",
                "daily_wage" to "દૈનિક મજૂરી (₹)",
                "search_contact" to "નામ અથવા મોબાઇલ નંબર શોધો",
                "saved_contacts" to "તમારા સાચવેલા સંપર્કો",
                "permission_contacts_title" to "સંપર્ક પરવાનગી જરૂરી છે",
                "permission_contacts_desc" to "કારીગરો ઉમેરવા માટે સંપર્ક પરવાનગી આપો.",
                "allow_contacts" to "સંપર્ક પરવાનગી આપો",
                "pick_from_device" to "સંપર્કોમાંથી પસંદ કરો",
                "refresh_contacts" to "રીફ્રેશ સંપર્કો",
                "cash_in" to "+ રોકડ આવક",
                "cash_out" to "- રોકડ જાવક",
                "cash_in_label" to "રોકડ આવક",
                "cash_out_label" to "રોકડ જાવક",
                "balance" to "બેલેન્સ",
                "view_report" to "રિપોર્ટ જુઓ",
                "search_transactions" to "વ્યવહાર શોધો",
                "no_transactions" to "આ મહિને કોઈ વ્યવહાર નથી",
                "date" to "તારીખ",
                "notes" to "નોંધ",
                "amount" to "₹ રકમ",
                "profile_info" to "પ્રોફાઇલ માહિતી",
                "business_name" to "ધંધા / કોન્ટ્રાક્ટરનું નામ",
                "account_email" to "ખાતું / ઇમેઇલ",
                "mobile" to "મોબાઇલ",
                "general" to "ગૂગલ ડ્રાઇવ અને સામાન્ય",
                "drive_backup" to "ગૂગલ ડ્રાઇવ બેકઅપ અને આયાત",
                "privacy_policy" to "ગોપનીયતા નીતિ",
                "terms_conditions" to "નિયમો અને શરતો",
                "rating_feedback" to "રેટિંગ અને પ્રતિસાદ આપો",
                "logout" to "લૉગ આઉટ",
                "select_language" to "ભાષા પસંદ કરો",
                "save" to "સાચવો",
                "cancel" to "રદ કરો",
                "ok" to "બરાબર",
                "present" to "હાજર (P)",
                "absent" to "ગેરહાજર (A)",
                "half_day" to "અડધો દિવસ (HD)",
                "overtime" to "ઓવરટાઇમ (OT)",
                "calendar" to "કેલેન્ડર"
            ),
            "bn" to mapOf(
                "labor" to "শ্রমিক",
                "cash_book" to "ক্যাশ বুক",
                "settings" to "সেটিংস",
                "add_labor" to "শ্রমিক যোগ করুন",
                "add_staff" to "কর্মী যোগ করুন",
                "non_contact_staff" to "সরাসরি কর্মী তথ্য দিন",
                "enter_labor_name" to "শ্রমিকের নাম লিখুন",
                "mobile_number" to "মোবাইল নম্বর",
                "daily_wage" to "দৈনিক মজুরি (₹)",
                "search_contact" to "নাম বা মোবাইল নম্বর দিয়ে খুঁজুন",
                "saved_contacts" to "আপনার সংরক্ষিত পরিচিতি",
                "permission_contacts_title" to "পরিচিতি অনুমতি প্রয়োজন",
                "permission_contacts_desc" to "পরিচিতি থেকে শ্রমিক যোগ করার জন্য অনুমতি দিন।",
                "allow_contacts" to "অনুমতি দিন",
                "pick_from_device" to "পরিচিতি থেকে নির্বাচন করুন",
                "refresh_contacts" to "পরিচিতি রিফ্রেশ করুন",
                "cash_in" to "+ ক্যাশ ইন",
                "cash_out" to "- ক্যাশ আউট",
                "cash_in_label" to "ক্যাশ ইন (জমা)",
                "cash_out_label" to "ক্যাশ আউট (খরচ)",
                "balance" to "ব্যালেন্স",
                "view_report" to "রিপোর্ট দেখুন",
                "search_transactions" to "লেনদেন খুঁজুন",
                "no_transactions" to "এই মাসে কোন লেনদেন নেই",
                "date" to "তারিখ",
                "notes" to "বিবরণ",
                "amount" to "₹ পরিমাণ",
                "profile_info" to "প্রোফাইল তথ্য",
                "business_name" to "ব্যবসা / ঠিকাদারের নাম",
                "account_email" to "অ্যাকাউন্ট / ইমেল",
                "mobile" to "মোবাইল",
                "general" to "গুগল ড্রাইভ এবং সাধারণ",
                "drive_backup" to "গুগল ড্রাইভ ব্যাকআপ ও আমদানি",
                "privacy_policy" to "গোপনীয়তা নীতি",
                "terms_conditions" to "শর্তাবলী",
                "rating_feedback" to "রেটিং এবং মতামত দিন",
                "logout" to "লগ আউট",
                "select_language" to "ভাষা নির্বাচন করুন",
                "save" to "সংরক্ষণ",
                "cancel" to "বাতিল",
                "ok" to "ঠিক আছে",
                "present" to "উপস্থিত (P)",
                "absent" to "অনুপস্থিত (A)",
                "half_day" to "অর্ধ দিবস (HD)",
                "overtime" to "ওভারটাইম (OT)",
                "calendar" to "ক্যালেন্ডার"
            ),
            "ta" to mapOf(
                "labor" to "தொழிலாளர்",
                "cash_book" to "பணப் பதிவேடு",
                "settings" to "அமைப்புகள்",
                "add_labor" to "தொழிலாளர் சேர்க்க",
                "add_staff" to "பணியாளர் சேர்க்க",
                "non_contact_staff" to "நேரடி பணியாளர் தகவல்",
                "enter_labor_name" to "தொழிலாளர் பெயர்",
                "mobile_number" to "மொபைல் எண்",
                "daily_wage" to "தினசரி கூலி (₹)",
                "search_contact" to "பெயர் அல்லது மொபைல் எண் தேடவும்",
                "saved_contacts" to "சேமிக்கப்பட்ட தொடர்புகள்",
                "permission_contacts_title" to "தொடர்பு அனுமதி தேவை",
                "permission_contacts_desc" to "தொடர்புகளிலிருந்து சேர்க்க அனுமதி வழங்கவும்.",
                "allow_contacts" to "அனுமதி வழங்கவும்",
                "pick_from_device" to "தொடர்புகளில் இருந்து தேர்ந்தெடுக்கவும்",
                "refresh_contacts" to "புதுப்பிக்கவும்",
                "cash_in" to "+ பணம் வரவு",
                "cash_out" to "- பணம் பற்று",
                "cash_in_label" to "பணம் வரவு",
                "cash_out_label" to "பணம் பற்று",
                "balance" to "மீதித் தொகை",
                "view_report" to "அறிக்கையைப் பார்",
                "search_transactions" to "பரிவர்த்தனைகளைத் தேடுங்கள்",
                "no_transactions" to "இந்த மாதம் பரிவர்த்தனைகள் இல்லை",
                "date" to "தேதி",
                "notes" to "குறிப்புகள்",
                "amount" to "₹ தொகை",
                "profile_info" to "சுயவிவர தகவல்",
                "business_name" to "தொழில் / ஒப்பந்ததாரர் பெயர்",
                "account_email" to "கணக்கு / மின்னஞ்சல்",
                "mobile" to "மொபைல்",
                "general" to "கூகிள் டிரைவ் மற்றும் பொது",
                "drive_backup" to "கூகிள் டிரைவ் காப்பு மற்றும் இறக்குமதி",
                "privacy_policy" to "தனியுரிமைக் கொள்கை",
                "terms_conditions" to "விதிமுறைகள் & நிபந்தனைகள்",
                "rating_feedback" to "மதிப்பீடு மற்றும் கருத்து தெரிவிக்கவும்",
                "logout" to "வெளியேறு",
                "select_language" to "மொழியைத் தேர்ந்தெடுக்கவும்",
                "save" to "சேமிக்கவும்",
                "cancel" to "ரத்து செய்",
                "ok" to "சரி",
                "present" to "வந்தவர் (P)",
                "absent" to "வராதவர் (A)",
                "half_day" to "அரை நாள் (HD)",
                "overtime" to "கூடுதல் நேரம் (OT)",
                "calendar" to "நாட்காட்டி"
            )
        )

        return translations[langCode]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
